### ISSUE TITLE
Multiple Daemons

### ISSUE THREAD

**Issue by 11of12** [BYUCamachoLab/pyrolab#34]
Multiple daemons do not configure in pyrolab on a single computer: 

for example, this code will produce nameservers only for the ones registered under asgard.lockable 

```
version: '1.0'

nameservers:
  production:
    host: camacholab.ee.byu.edu
    ns_port: 9090
    broadcast: false
    ns_bchost: null
    ns_bcport: 9091
    ns_autoclean: 0.0
    storage: memory

daemons:
  asgard.lockable:
    module: pyrolab.server
    classname: LockableDaemon
    host: public
    port: 0
    unixsocket: null
    nathost: null
    natport: 0
    servertype: thread
    nameservers:
    - production
  asgard.camera:
    module: pyrolab.server
    classname: LockableDaemon
    host: public
    port: 0
    unixsocket: null
    nathost: null
    natport: 0
    servertype: thread
    nameservers:
    - production

services:
  asgard.diamondhead:
    module: pyrolab.drivers.cameras.uc480
    classname: UC480
    parameters:
      serialno: 4103247225
    description: ThorCam
    instancemode: single
    daemon: asgard.lockable
    nameservers:
    - production
  asgard.diablito:
    module: pyrolab.drivers.motion.z8xx # pyrolab.drivers.motion.kmts25e
    classname: Z825B # KMTS25E
    parameters:
      serialno: 27504851
    description: Hydrogen Torch Stage
    instancemode: single
    daemon: asgard.lockable
    nameservers:
    - production
  asgard.kramer:
    module: pyrolab.drivers.motion.z8xx
    classname: Z825B
    parameters:
      serialno: 27003366
    description: Camera Stage Vertical
    instancemode: single
    daemon: asgard.lockable
    nameservers:
    - production
  asgard.devros:
    module: pyrolab.drivers.motion.z8xx
    classname: Z825B # KMTS25E
    parameters:
      serialno: 27601902
    description: Left Fibre Puller
    instancemode: single
    daemon: asgard.lockable
    nameservers:
    - production
  asgard.venom:
    module: pyrolab.drivers.motion.z8xx
    classname: Z825B # KMTS25E
    parameters:
      serialno: 27003497
    description: Right Fibre Puller
    instancemode: single
    daemon: asgard.camera
    nameservers:
    - production
  asgard.test:
    module: pyrolab.drivers.motion.prm1z8
    classname: PRM1Z8
    parameters:
      serialno: 27601950
    description: Testing using rotational stage
    instancemode: single
    daemon: asgard.lockable
    nameservers: 
    - production
    
autolaunch:
  nameservers: []
  daemons:
  - asgard.lockable
```

**Comment by sequoiap** [comment]
@11of12 Note the autolaunch section only brings up one daemon when you run ```pyrolab up```. If you want two daemons to start automatically, they must be individually listed, e.g.:

```
autolaunch:
    nameservers: []
    daemons:
    - asgard.lockable
    - asgard.camera
```

Does this resolve the problem?
